geekshop/authapp/urls.py
from django.urls import path, re_path
import authapp.views as authapp
import os
from pathlib import PurePath

app_name = PurePath(os.path.dirname(__file__)).parts[-1]

urlpatterns = [
    path('login/', authapp.Login.as_view(), name='login'),
    path('logout/', authapp.Logout.as_view(), name='logout'),
    path('register/', authapp.CreateProfile.as_view(), name='register'),
    path('edit/', authapp.EditProfile.as_view(), name='edit'),
    path('password/edit', authapp.PasswordChange.as_view(), name='edit_password'),
    path('quick_login/<slug:slug>/', authapp.QuickLogin.as_view(), name='quick_login'),
    path('verify/<str:username>/<str:activation_key>/', authapp.VerifyRedirect.as_view(), name='verify'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('additional/', include('django.contrib.flatpages.urls')),
    re_path(r'^rosetta/', include('rosetta.urls')),
    path('', include("social_django.urls", namespace="social")),

    path('auth/', include('authapp.urls', namespace='auth')),
    path('', include('mainapp.urls', namespace='mainapp')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.EMAIL_FILE_PATH, document_root=settings.EMAIL_ROOT)

    import debug_toolbar
    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

geekshop/mainapp/urls.py
from django.urls import path, re_path
import mainapp.views as mainapp
import os
from pathlib import PurePath

app_name = PurePath(os.path.dirname(__file__)).parts[-1]

urlpatterns = [
    path('', mainapp.IndexView.as_view(), name='main'),
    path('new/', mainapp.IndexView.as_view(), name='new'),

    path('catalog/', mainapp.CatalogView.as_view(), name='catalog'),
    path('catalog/product_<int:pk>/', mainapp.ProductDetail.as_view(), name='product'),
    path('catalog/<str:href>/', mainapp.CatalogView.as_view(), name='category'),
    path('showroom/', mainapp.ErrorView.as_view(), name='showroom'),
    path('contacts/', mainapp.ContactView.as_view(), name='contacts'),
    path('search/', mainapp.SearchView.as_view(), name='search'),

    path('category/add/', mainapp.ProductCategoryCreate.as_view(), name='add_category'),
    path('category/edit/<slug:slug>', mainapp.ProductCategoryUpdate.as_view(), name='edit_category'),
    path('category/delete/<slug:slug>', mainapp.ProductCategoryDelete.as_view(), name='del_category'),

    path('product/add/', mainapp.ProductCreate.as_view(), name='add_product'),
    path('product/edit/<int:pk>', mainapp.ProductUpdate.as_view(), name='edit_product'),
    path('product/delete/<int:pk>', mainapp.ProductDelete.as_view(), name='del_product'),

    path('picture/add/<int:related_obj>', mainapp.PictureCreate.as_view(), name='add_picture'),
    path('picture/edit/<int:pk>', mainapp.PictureUpdate.as_view(), name='edit_picture'),
    path('picture/del/<int:pk>', mainapp.PictureDelete.as_view(), name='del_picture'),

    path('orders/add_<int:ware>', mainapp.OrderCreate.as_view(), name='add_order'),
    path('orders/edit_<int:ware>', mainapp.OrderUpdate.as_view(), name='edit_order'),
    path('orders/del_<int:ware>', mainapp.OrderDelete.as_view(), name='del_order'),

    path('basket/', mainapp.InvoiceDetail.as_view(), name='basket'),
    path('invoice/confirm/', mainapp.InvoiceUpdate.as_view(), name='edit_invoice'),

    path('staff/invoices/', mainapp.StaffInvoiceList.as_view(), name='staff_invoices'),
    path('staff/invoice/create/', mainapp.StaffInvoiceCreate.as_view(), name='add_staff_invoice'),
    path('staff/invoice/<int:pk>', mainapp.StaffInvoiceUpdate.as_view(), name='edit_staff_invoice'),
    path('order_formset/<int:invoice>/<int:num>/<int:ware>/', mainapp.order_formset_ajax, name='order_formset'),

]

geekshop/mainapp/views.py
from django.contrib import messages
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q
from django.http import HttpResponseRedirect, JsonResponse
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.timezone import now
from django.utils.translation import ugettext_lazy as _
from django.views.generic import ListView, DetailView, UpdateView, TemplateView, CreateView, DeleteView

from mainapp.forms import ProductForm, ProductCategoryForm, PictureForm, PriceFormSet, \
                          StaffInvoiceForm, StaffOrderFormSet
from .models import *


def add_links_href_app(lst_lst_name_href, app='mainapp'):
    """setattr 'href_app' for links_menu_products without category
    "lst_lst_name" - list should look like: [[name_page_1, name_url_1], [name_page_2, name_url_2], [etc.]]"""
    new_list = []
    for link in lst_lst_name_href:
        new_list.append({'name': f'{link[0]}', 'href': f'{link[1]}', 'href_app': f'{app}:{link[1]}'})
    return new_list


class UserStaffTest(UserPassesTestMixin):
    """docstring for test user is staff"""
    def test_func(self):
        return self.request.user.is_staff

    def handle_no_permission(self):
        return HttpResponseRedirect('/')


class IndexView(ListView):
    """docstring for page home"""
    template_name = 'mainapp/index.html'
    model = Product

    def get_queryset(self):
        response = super().get_queryset()
        if 'new' == self.request.resolver_match.url_name:
            self.kwargs['products_featORnew'] = Product.objects.get_products_new()[:4]
        else:
            self.kwargs['products_featORnew'] = Product.objects.get_products_featured()[:4]

        return response, self.kwargs

    def post(self, request, *args, **kwargs):
        if self.request.is_ajax():
            super().get(request, *args, **kwargs)
            context = {'products': self.kwargs['products_featORnew'],
                       'class': 'bbA_img'}
            context = render_to_string('mainapp/includes/inc_products.html', context)
            response = JsonResponse({'result': context})

            return response
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products_trend = Product.objects.get_products_trend()
        products_exclusive = Product.objects.get_products_exclusive()

        context.update({'caption': _('Home Interior'),
                        'links_no_cat': add_links_href_app([['Featured', 'main'], ['New', 'new']]),
                        'products_featORnew': self.kwargs['products_featORnew'],
                        'products_slider_1': Product.objects.get_products_slider_1(),
                        'products_slider_2': Product.objects.get_products_slider_2(),
                        'products_trend_1': products_trend[:6],
                        'products_trend_2': products_trend[6:10],
                        'products_exclusive_1': products_exclusive[:2],
                        'products_exclusive_2': products_exclusive[2:3],
                        })
        return context


class CatalogView(ListView):
    """docstring for page catalog"""
    model = Product
    paginate_by = 6
    ordering = ('id',)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['caption'] = _('Products')
        context.update({'links_no_cat': add_links_href_app([['All', 'catalog']]),
                        'links_menu_products': ProductCategory.objects.get_category(),
                        'products_exclusive': Product.objects.get_products_exclusive(),
                        })
        return context

    def render_to_response(self, context, **response_kwargs):
        if self.request.is_ajax():
            self.template_name = 'mainapp/includes/inc_categories.html'

        return super().render_to_response(context, **response_kwargs)

    def get_queryset(self):
        response = super().get_queryset()
        if 'href' in self.kwargs:
            href = self.kwargs.get('href', '')
            response = Product.objects.get_products_incategory(href)
        return response.select_related('category')


class ProductDetail(DetailView):
    """docstring for page product"""
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['caption'] = _('Product')

        obj = self.object
        obj.up_views()
        obj_prices = obj.prices.get_price_user(self.request.user)
        context.update({
            'object_list': Product.objects.get_product_related(obj),
            'price_without_discount': obj_prices.price_base,
            'price_now': obj_prices.price_user,
        })
        return context


class ProductCreate(UserStaffTest, SuccessMessageMixin, CreateView):
    """docstring for add product"""
    model = Product
    form_class = ProductForm
    success_message = _('Product added')

    def get_success_url(self):
        pk = self.object[0].related_obj.pk
        return reverse_lazy('mainapp:product', kwargs={'pk': pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['caption'] = _('Add product')
        formset = PriceFormSet()
        context['prices'] = formset
        if self.request.POST:
            context['prices'] = PriceFormSet(self.request.POST)

        statuses = UserStatus.objects.all()
        context['prices'].extra = len(statuses)
        for i, form in enumerate(formset.forms):
            form.initial['group'] = statuses[i]
        return context

    def form_valid(self, form):
        formset = PriceFormSet(self.request.POST)

        if not formset.is_valid():
            return self.form_invalid(form)
        else:
            formset.instance = form.save()
            return super().form_valid(formset)


class ProductUpdate(UserStaffTest, SuccessMessageMixin, UpdateView):
    """docstring for edit product"""
    model = Product
    form_class = ProductForm
    success_message = _('Product edited')

    def get_success_url(self):
        return reverse_lazy('mainapp:product', args=[self.kwargs['pk']])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['caption'] = _('Edit product')
        context['prices'] = PriceFormSet(instance=self.get_object())
        if self.request.POST:
            context['prices'] = PriceFormSet(self.request.POST, instance=self.get_object())
        context['prices'].extra = 0
        return context

    def form_valid(self, form):
        formset = PriceFormSet(self.request.POST, instance=self.get_object())

        if not formset.is_valid():
            return self.form_invalid(form)
        else:
            formset.instance = form.save()
            return super().form_valid(formset)


class ProductDelete(UserStaffTest, SuccessMessageMixin, DeleteView):
    """docstring for delete product"""
    model = Product
    success_message = _('Product deleted')

    def get_success_url(self):
        messages.success(self.request, self.success_message)
        return reverse_lazy('mainapp:catalog')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['caption'] = 'Delete product'
        return context


class PictureCreate(UserStaffTest, SuccessMessageMixin, CreateView):
    """docstring for add product"""
    model = Picture
    form_class = PictureForm
    success_message = _('Picture added')

    def form_valid(self, form):
        form.instance.related_obj_id = self.kwargs.get('related_obj')
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('mainapp:edit_product', args=(self.object.related_obj.id or 0,))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['related_obj'] = self.kwargs.get('related_obj')
        context['caption'] = 'Add picture'
        return context


class PictureUpdate(UserStaffTest, SuccessMessageMixin, UpdateView):
    """docstring for edit product"""
    model = Picture
    form_class = PictureForm
    success_message = _('Picture edited')

    def get_success_url(self):
        return reverse_lazy('mainapp:edit_product', args=(self.object.related_obj.id or 0,))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['caption'] = 'Edit picture'
        return context


class PictureDelete(UserStaffTest, SuccessMessageMixin, DeleteView):
    """docstring for delete product"""
    model = Picture
    success_message = _('Picture marked as inactive')

    def get_success_url(self):
        messages.success(self.request, self.success_message)
        return reverse_lazy('mainapp:product',  kwargs={'pk': self.get_object().related_obj.id})

    def delete(self, request, *args, **kwargs):
        success_url = self.get_success_url()
        self.get_object().delete()
        return HttpResponseRedirect(success_url)


class ProductCategoryCreate(UserStaffTest, SuccessMessageMixin, CreateView):
    """docstring for add product"""
    model = ProductCategory
    form_class = ProductCategoryForm
    success_message = _('Category added')

    def get_success_url(self):
        return reverse_lazy('mainapp:category', kwargs={'href': self.object.href})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['caption'] = _('Add category')
        return context


class ProductCategoryUpdate(UserStaffTest, SuccessMessageMixin, UpdateView):
    """docstring for edit product"""
    model = ProductCategory
    slug_field = 'href'
    form_class = ProductCategoryForm

geekshop/mainapp/templates/mainapp/includes/inc_buy.html
{% load staticfiles i18n %}
<form method="post" action="{% url 'mainapp:edit_order' product.id %}">
    <button type="submit" name="add" value="{{ product.id }}" class="order_us">
        {% csrf_token %}
        {% trans 'Buy' %}<img src="{% static 'img/arrow.png' %}" alt="">
    </button>
</form>

geekshop/mainapp/templates/mainapp/includes/inc_categories.html
{% load staticfiles i18n %}
<div class="line_menu">
    {% include 'mainapp/includes/inc_menu_products.html' with links=links_no_cat objects=links_menu_products %}
</div>
{% if is_paginated %}
    {% include 'mainapp/includes/inc_pagination.html' %}
{% endif %}

{% if object_list %}
    <div class="block_img group_c">
        {% include 'mainapp/includes/inc_products.html' with class='bbB_img' products=object_list %}
    </div>
{% else %}
    <p>{% trans 'Unfortunately, there are no products in this category yet.' %}</p>
{% endif %}

geekshop/mainapp/templates/mainapp/includes/inc_menu.html
{% load staticfiles i18n %}

<div class="header header_adaptive">
    <a href="{% url 'mainapp:main' %}" class="logo">
        <img src="{% static 'img/logo.png' %}" alt="logo">
    </a>
    <nav>
        <ul class="menu">
            {% for link in links_menu %}
                <li><a href="{% url link.href_app %}"
                       class="{% if link.href == current_url or link.href == page_url %}active_menu{% endif %}">
                    {{ link.name }}
                </a>
                </li>
            {% endfor %}
            {% if user.is_authenticated %}
                <li>
                    <a href="#">{% trans 'Hello, ' %}{{ user.first_name|default:user.username }}</a>
                    <ul>
                        {% if user.is_superuser or user.is_staff %}
                            <li><a href="{% url 'admin:index' %}">{% trans 'Admin panel' %}</a></li>
                        {% endif %}
                        <li><a href="{% url 'auth:edit' %}">{% trans 'Edit profile' %}</a></li>
                        <li><a href="{% url 'auth:logout' %}">{% trans 'Log out' %}</a></li>
                    </ul>
                </li>

            {% else %}
                <li><a href="{% url 'auth:login' %}">{% trans 'Log in' %}</a></li>
            {% endif %}
            <li><a href="{% url 'mainapp:search' %}" class="button_search"></a></li>
            {% if user.is_authenticated %}
                {% if user.is_staff %}
                    <li>
                        <a href="{% url 'mainapp:staff_invoices' %}" class="button_invoices {% if invoices_count == 0 %}button_invoices_no{% endif %}">
                            <img src="{% static 'img/invoices.png' %}" alt="">
                            {% if invoices_count != 0 %}
                                <span class="invoices_count">{{ invoices_count }}</span>
                            {% endif %}
                        </a>
                    </li>
                {% endif %}
                <li>
                    <a href="{% url 'mainapp:basket' %}" class="button_basket">
                        <img src="{% static 'img/basket.png' %}" alt="">
                        {% if basket_count != 0 %}
                            <span class="basket_count">{{ basket_count }}</span>
                        {% endif %}
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
</div>
{% include "mainapp/includes/inc_messages.html" %}

geekshop/mainapp/templates/mainapp/includes/inc_menu_products.html
{% load staticfiles i18n %}
{% with current_kwargs=request.resolver_match.kwargs.href  %}
    <ul>

        {% for link in links %}
            <li class="no_cat">
                <form action="{% url link.href_app %}">
                    {% csrf_token %}
                    <input type="hidden" name="url" value="{{ link.href }}">
                    <a href="{% url link.href_app %}"
                       class="{% if link.href == current_url %}active_menu{% endif %}">
                        {% if page_url == '/' %}
                            {{ link.name|capfirst }}
                        {% else %}
                            {{ link.name|upper }}
                        {% endif %}
                    </a>
                </form>
            </li>
        {% endfor %}

        {% for object in objects %}
            <li>
                <a href="{% url 'mainapp:category' object.href %}"
                   class="{% if object.href == current_kwargs %}active_menu{% endif %}">
                    {% if page_url == '/' %}
                        {{ object.name|capfirst }}
                    {% else %}
                        {{ object.name|upper }}
                    {% endif %}
                </a>
            </li>
        {% endfor %}


        {% if user.is_superuser or user.is_staff %}
            {% if current_url == 'catalog' or current_url == 'category' %}
                <li><a href="{% url 'mainapp:add_category' %}"><span>{% trans 'Add' %}</span></a></li>
                {% if current_kwargs %}
                    <li><a href="{% url 'mainapp:edit_category' current_kwargs %}">{% trans 'Edit' %}</a></li>
                    <li><a href="{% url 'mainapp:del_category' current_kwargs %}">{% trans 'Delete' %}</a></li>
                {% endif %}


            {% endif %}
        {% endif %}
    </ul>


{% endwith %}

geekshop/mainapp/templates/mainapp/includes/inc_messages.html
<ul class="messages padding-site">
    {% if messages %}
        {% for message in messages %}
            {% if forloop.last %}<li>{{ message|safe }}</li>{% endif %}
        {% endfor %}
    {% else %}
        <li></li>
    {% endif %}
</ul>

geekshop/mainapp/templates/mainapp/includes/inc_order_formset.html
{% load i18n %}

{% for field in form.visible_fields %}
    <td>
        {% if forloop.first %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
        {% endif %}
        {{ field.errors.as_ul }}
        {{ field }}
    </td>
{% endfor %}

{% if object %}
    {% if form.ware.value %}
        {% if not ajax_price %}
            {% for iter_price in form.instance.ware.prices.all %}
                {% if iter_price.group == customer_status %}
                    {% include 'mainapp/includes/inc_price_staff_invoice.html' %}
                {% endif %}
            {% endfor %}

        {% else %}
            {% include 'mainapp/includes/inc_price_staff_invoice.html' %}
        {% endif %}

        <td><a href="{% url 'mainapp:product' form.ware.value %}" class="order_us">{% trans 'View' %}</a></td>
    {% else %}
        <td></td>
        <td></td>
        <td></td>
    {% endif %}
{% endif %}

<td class="delete_row"></td>

geekshop/mainapp/templates/mainapp/includes/inc_order_us.html
{% load staticfiles i18n %}

<a class="order_us" href="{% url 'mainapp:product' product.id %}"><span>{% trans 'Order Us' %}</span><img src="{% static 'img/arrow.png' %}" alt=""></a>

geekshop/mainapp/templates/mainapp/includes/inc_pagination.html
{% load i18n %}
<div class="pagination group_c">
    <span>
    {% if page_obj.has_previous %}
        <p class="block-first">
        {% if page_obj.previous_page_number > 1 %}
            <a href="{{path}}?page=1">{% trans " << " %}</a>
        {% endif %}
            <a href="{{path}}?page={{ page_obj.previous_page_number }}"
               class="{% if page_obj.previous_page_number == 1 %}padd-one-button{% endif %}">{% trans " < " %}</a>
        </p>
    {% endif %}
    </span>

    <p class="{% if page_obj.has_previous and page_obj.has_next %}block
                {% elif page_obj.has_next %}block-first padd-bl-center
                    {% else %}block-last padd-bl-center{% endif %}">{% trans 'Page ' %}{{ page_obj.number }}{% trans ' of ' %}{{ paginator.num_pages }}</p>

    <span>
    {% if page_obj.has_next %}
        <p class="block-last">
        <a href="{{path}}?page={{ page_obj.next_page_number }}"
           class="{% if paginator.num_pages == page_obj.next_page_number %}padd-one-button{% endif %}">{% trans " > " %}</a>
            {% if paginator.num_pages != page_obj.next_page_number %}
                <a href="{{path}}?page={{ paginator.num_pages }}">{% trans " >> " %}</a>
            {% endif %}
        </p>
    {% endif %}
    </span>
</div>

geekshop/mainapp/templates/mainapp/includes/inc_picture_edit.html
{% load staticfiles i18n %}
<div class="block_img">

    {% if add %}
        <div class="bbA_img product group_c">
            <img class="product_img" src="{% static 'img/navigate_add.png' %}" alt="{{ image.name }}">
            <div class="product_text">
                <a class="arrow" href="{% url 'mainapp:add_picture' object.id %}"></a>
                <h2>{% trans 'Add picture' %}</h2>
            </div>
        </div>
    {% endif %}

    {% for image in images %}
        <div class="bbA_img  product group_c {% if is_slider %}bb_slider{% endif %}">
            <img class="product_img" src="{{ image.image.url }}" alt="{{ image.name }}">
            <div class="product_text">
                <h2>{{ image.name }}</h2>
                <a class="order_us" href="{% url 'mainapp:edit_picture' image.id %}">{% trans 'Edit' %}</a><br>
                <a class="order_us" href="{% url 'mainapp:del_picture' image.id %}">{% trans 'Delete' %}</a>
            </div>
        </div>
    {% endfor %}

</div>

geekshop/mainapp/templates/mainapp/includes/inc_price_staff_invoice.html
<td class="order-price">
    {% if ajax_price %}{{ ajax_price }}{% else %}{{ iter_price.price_user }}{% endif %}
</td>
<td class="order-total_cost">
    {% if ajax_price %}{{ ajax_price }}{% else %}{{ form.instance.get_total_cost }}{% endif %}
</td>

geekshop/mainapp/templates/mainapp/includes/inc_prod_picture_main.html
{% if product.pictures.all %}
    <img class="{{ class }}" src="{{ product.pictures.get_main.0.image.url }}" alt="{{ product.name }}">
    {% if product.category.discount != 0 %}
        <span class="discount">-{{product.category.discount}}%</span>
        <span class="discount_line1"></span>
        <span class="discount_line2"></span>
    {% endif %}
    {% else %}
    <img class="{{ class }}" src="/media/products_images/default_product.jpg" alt="">
{% endif %}

geekshop/mainapp/templates/mainapp/includes/inc_products.html
{% load staticfiles i18n %}
{% if user.is_superuser or user.is_staff %}
{% if current_url == 'catalog' %}
    <div class="{{ class }} product group_c">
        <img class="product_img" src="{% static 'img/navigate_add.png' %}" alt="{{ product.name }}">
        <div class="product_text">
            <a class="arrow" href="{% url 'mainapp:add_product' %}"></a>
            <h2>{% trans 'Add product' %}</h2>
        </div>
    </div>
{% endif %}
{% endif %}

{% for product in products %}
        <div class="{{ class }} product group_c">
            {% include 'mainapp/includes/inc_prod_picture_main.html' with class='product_img' %}
            <div class="product_text">
                <a class="arrow" href="{% url 'mainapp:product' product.id %}"></a>
                <h2>{{ product.name }}</h2>
                <p>{{ product.short_desc }}</p>
            </div>
        </div>
{% endfor %}

geekshop/mainapp/templates/mainapp/includes/inc_slider.html
{% load staticfiles i18n %}
<div class="slider {{ class }} group_a">
    <ul>
        {% for product in products %}
            <li>
                <img class="slider_img" src="{{ product.pictures.get_slider.0.image.url }}" alt="{{ product.name }}">
                <div class="slider_text">
                    <h3>{% trans 'TRENDING' %}</h3>
                    <h2>{{ product.name }}</h2>
                    <p>{{ product.short_desc }}</p>
                    {% include 'mainapp/includes/inc_order_us.html' with product=product %}
                </div>
            </li>
        {% endfor %}
    </ul>
</div>

geekshop/mainapp/templates/mainapp/includes/snip_explore_all.html
{% load staticfiles i18n %}

<a class="explore-all" href="{% url 'mainapp:catalog' %}"><span>{% trans 'explore all' %}</span><img src="{% static 'img/arrow.png' %}" alt=""></a>