geekshop/authapp/urls.py
from django.urls import path, re_path
import authapp.views as authapp
import os
from pathlib import PurePath

app_name = PurePath(os.path.dirname(__file__)).parts[-1]

urlpatterns = [
    path('login/', authapp.Login.as_view(), name='login'),
    path('logout/', authapp.Logout.as_view(), name='logout'),
    path('register/', authapp.CreateProfile.as_view(), name='register'),
    path('edit/', authapp.EditProfile.as_view(), name='edit'),
    path('password/edit', authapp.PasswordChange.as_view(), name='edit_password'),
    path('quick_login/<slug:slug>/', authapp.QuickLogin.as_view(), name='quick_login'),
    path('verify/<str:username>/<str:activation_key>/', authapp.VerifyRedirect.as_view(), name='verify'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('additional/', include('django.contrib.flatpages.urls')),
    re_path(r'^rosetta/', include('rosetta.urls')),
    path('', include("social_django.urls", namespace="social")),

    path('auth/', include('authapp.urls', namespace='auth')),
    path('', include('mainapp.urls', namespace='mainapp')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.EMAIL_FILE_PATH, document_root=settings.EMAIL_ROOT)

    import debug_toolbar
    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

geekshop/authapp/models.py
from datetime import timedelta

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.timezone import now
from django.utils.translation import ugettext_lazy as _


class UserStatus(models.Model):
    """ShopUser status"""
    class Meta:
        verbose_name = _('User status')
        verbose_name_plural = _('Users statuses')
        ordering = ('sort',)

    DEFAULT = 'df'
    BRONZE = 'br'
    SILVER = 'sl'
    GOLD = 'gl'

    Status_KIND_CHOICES = (
        (DEFAULT, 'Default'),
        (BRONZE, 'Bronze'),
        (SILVER, 'Silver'),
        (GOLD, 'Gold'),
    )

    description = models.TextField(_('description'), blank=True)
    status = models.CharField(max_length=2, choices=Status_KIND_CHOICES, default=DEFAULT)
    sort = models.IntegerField(_('sort'), default=0, null=True, blank=True)

    def __str__(self):
        return f'{self.get_status_display()}'


def default_user_status():
    return UserStatus.objects.get(status=UserStatus.DEFAULT).pk


class ShopUser(AbstractUser):
    avatar = models.ImageField(upload_to='users_avatars', blank=True, default='users_avatars/default_avatar.jpg')
    age = models.PositiveIntegerField(verbose_name='age', null=True)
    activation_key = models.CharField(verbose_name='confirmation key', max_length=128, blank=True)
    status = models.ForeignKey(UserStatus, verbose_name=_(u'Customer status'), related_name='users',
                               default=default_user_status(), on_delete=models.SET_DEFAULT)

    def is_activation_key_expired(self):
        return now() >= self.date_joined + timedelta(hours=48)

geekshop/authapp/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UserChangeForm
from .models import ShopUser

from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _

from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth.hashers import make_password


class MutualWidget:
    """Class for forms MutualWidgets """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ShopUserLoginForm(MutualWidget, AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = '__all__'


class ShopUserRegisterForm(MutualWidget, UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'password1', 'password2', 'email', 'age', 'avatar')

    def send_verify_mail(self, data, activation_key):
        verify_link = reverse_lazy('authapp:verify', args=[data['username'], activation_key])

        title = f'Verification for {data["username"]}'
        message = f'To confirm your account {data["username"]} click on the link:\
                      \n{settings.DOMAIN_NAME}{verify_link}'

        return send_mail(title, message, settings.EMAIL_HOST_USER, [data['email']], fail_silently=True, )

    def clean(self):
        activation_key = make_password(None)
        send_ver_mail = self.send_verify_mail(self.cleaned_data, activation_key)

        if send_ver_mail:
            user = super().save(commit=False)
            user.is_active = False
            user.activation_key = activation_key
            user.save()
        else:
            self.add_error(None, _('Error sending message to confirm registration. Please try later.'))

        return super().clean()


class ShopUserEditForm(MutualWidget, UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'email', 'age', 'avatar', 'password', 'status',)

    def __init__(self, *args, **kwargs):
        super(ShopUserEditForm, self).__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()
        self.fields['status'].widget.attrs['disabled '] = True

geekshop/authapp/views.py
import os

from django.conf import settings
from django.contrib import auth
from django.contrib import messages
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import HttpResponseRedirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.views.generic import CreateView, UpdateView, DeleteView, RedirectView

from authapp.forms import ShopUserLoginForm, ShopUserRegisterForm, ShopUserEditForm
from authapp.models import ShopUser


class Login(SuccessMessageMixin, UserPassesTestMixin, LoginView):
    """docstring for LoginView"""
    template_name = 'authapp/login.html'
    success_message = _('Log in success')
    form_class = ShopUserLoginForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Log in')
        if not settings.SOCIAL_AUTH_GOOGLE_OAUTH2_KEY:
            context['google_in_closed'] = 'disabled'
        if not settings.SOCIAL_AUTH_VK_OAUTH2_KEY:
            context['vk_in_closed'] = 'disabled'
        return context

    def test_func(self):
        return not self.request.user.is_authenticated

    def handle_no_permission(self):
        return HttpResponseRedirect('/')


class Logout(LogoutView):
    """docstring for logoutView"""
    success_message = _('Log out success')

    def get_next_page(self):
        next_page = super().get_next_page()
        if next_page:
            messages.success(self.request, self.success_message)
        return next_page


class CreateProfile(SuccessMessageMixin, CreateView):
    """docstring for RegisterProfile"""
    template_name = 'authapp/register.html'
    model = ShopUser
    form_class = ShopUserRegisterForm
    success_url = '/'
    success_message = _('Registration completed successfully')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Register')
        return context

    def form_valid(self, form):
        dirname = settings.EMAIL_FILE_PATH
        filenames = os.listdir(dirname)
        filepaths = [os.path.join(dirname, filename) for filename in filenames]

        self.success_message = _('A confirmation letter has been sent to your email. '
                                 f'<a href="/{filepaths[-1]}">(Click for view)<a>')

        return super().form_valid(form)


class EditProfile(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    """docstring for EditProfile"""
    template_name = 'authapp/edit.html'
    login_url = reverse_lazy('authapp:login')
    model = ShopUser
    form_class = ShopUserEditForm
    success_url = '/'
    success_message = _('Profile changed')

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Edit')
        return context


class DeleteProfile(DeleteView):
    """docstring for DelView"""
    model = ShopUser


class PasswordChange(LoginRequiredMixin, SuccessMessageMixin, PasswordChangeView):
    template_name = 'authapp/password_change_form.html'
    success_message = _('Password changed')
    success_url = reverse_lazy('authapp:edit')


class QuickLogin(SuccessMessageMixin, RedirectView):
    """quick login to the system"""
    pattern_name = 'mainapp:main'
    success_message = _('Log in success')

    def get_redirect_url(self, *args, **kwargs):
        slug = self.kwargs['slug']
        user = auth.authenticate(username=slug, password=slug)
        auth.login(self.request, user)
        messages.success(self.request, self.success_message)
        return super().get_redirect_url()


class VerifyRedirect(SuccessMessageMixin, RedirectView):
    pattern_name = 'mainapp:main'
    success_message = _('Thank you for registration, account is confirmed')

    def get_redirect_url(self, *args, **kwargs):
        activation_key = kwargs.get('activation_key')
        user = get_object_or_404(ShopUser, username=kwargs.get('username'))

        if user.activation_key == activation_key and not user.is_activation_key_expired():
            user.is_active = True
            user.save()
            auth.login(self.request, user, backend='django.contrib.auth.backends.ModelBackend',)
        else:
            self.success_message = _('Sorry, but activation key is invalid')

        messages.success(self.request, self.success_message)
        return super().get_redirect_url()

geekshop/authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load staticfiles i18n %}
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>

    {% block css %}
        <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
        <link rel="stylesheet" href="{% static 'css/fonts.css' %}">
        <link rel="stylesheet" href="{% static 'authapp/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'authapp/css/style.css' %}">
    {% endblock %}

    {% block js_script %}
        <script src="{% static 'js/jquery_3_2_1_min.js' %}?v={{ VERSION }}"></script>
        <script src="{% static 'authapp/js/bootstrap-filestyle.min.js' %}?v={{ VERSION }}"></script>
        <script src="{% static 'authapp/js/script.js' %}?v={{ VERSION }}"></script>
       {% endblock js_script %}
</head>
<body>
	<div class="container">
         <div class="login">
            <div class="h2 text-center head">
                {% block name_page %}
                    {% trans 'Login to the system' %}
                {% endblock %}
            </div>
            {% block content %}
            {% endblock %}
        </div>
	</div>
</body>
</html>

geekshop/authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}
{% load staticfiles i18n %}

{% block name_page %}
    {% trans 'Edit Profile' %}
{% endblock %}
{% block content %}
    <div class="user_avatar"><img src="{{ user.avatar.url }}"></div>
    <form class="form-horizontal" action="{% url 'auth:edit' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="form-control" type="submit" value="Save">
    </form>
    <a href="{% url 'authapp:edit_password' %}" class="">
        <button class="btn btn-round form-control">
            {% trans 'Change password' %}
        </button>
    </a>
    {% include 'authapp/includes/snip_button_home.html' %}

{% endblock %}

geekshop/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load staticfiles i18n %}
{% block title %}
    {{ title|title }}
{% endblock %}

{% block content %}
    <form class="form-horizontal" action="{% url 'auth:login' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <input class="form-control" type="submit" value="Sign in">
    </form>
    <a href="{% url 'auth:register' %}" class="">
        <button class="btn form-control">
            {% trans 'Sign up' %}
        </button>
    </a>


    <div class="h2 text-center head">{% trans 'Sign in with social network' %}</div>
    {% if google_in_closed or vk_in_closed %}
        <div class="alert alert-info">
            {% trans 'Sign in with' %}
            {% if google_in_closed %}Google+{% endif %}
            {% if google_in_closed and vk_in_closed %}, {% endif %}
            {% if vk_in_closed %}VK{% endif %}
            {% trans ' inactive due to confidentiality. If you are a developer, enter SECRET_API_KEY in settings.py for activation.' %}
        </div>
    {% endif %}

    <a href="{% url 'social:begin' 'google-oauth2' %}">
        <input {{ google_in_closed }} class="form-control" type="submit"  value="{% trans 'Google+' %}">
    </a>
    <a href="{% url 'social:begin' 'vk-oauth2' %}">
        <input {{ vk_in_closed }} class="form-control" type="submit" value="{% trans 'VK' %}">
    </a>


    <div class="h2 text-center head">{% trans 'Quick access' %}</div>
    <a href="{% url 'auth:quick_login' 'test' %}"><input class="form-control" type="submit" value="{% trans 'Login as User' %}"></a>
    <a href="{% url 'auth:quick_login' 'manager' %}"><input class="form-control" type="submit" value="{% trans 'Login as Manager' %}"></a>


    {% include 'authapp/includes/snip_button_home.html' %}
{% endblock %}

geekshop/authapp/templates/authapp/password_change_form.html
{% extends 'authapp/base.html' %}
{% load staticfiles i18n %}

{% block name_page %}
    {{ title }}
{% endblock %}
{% block content %}
    <div class="user_avatar"><img src="{{ user.avatar.url }}"></div>
    <form class="form-horizontal" action="{% url 'auth:edit_password' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="form-control" type="submit" value="Save">
    </form>
    {% include 'authapp/includes/snip_button_home.html' %}
{% endblock %}

geekshop/authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load staticfiles i18n %}

{% block name_page %}
    {% trans 'Register Profile' %}
{% endblock %}
{% block content %}
    <form class="form-horizontal" action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <input class="form-control" type="submit" value="Sign in">
    </form>
    {% include 'authapp/includes/snip_button_home.html' %}

{% endblock %}