geekshop/authapp/urls.py
from django.urls import path, re_path
import authapp.views as authapp
import os
from pathlib import PurePath

app_name = PurePath(os.path.dirname(__file__)).parts[-1]

urlpatterns = [
    path('login/', authapp.Login.as_view(), name='login'),
    path('logout/', authapp.Logout.as_view(), name='logout'),
    path('register/', authapp.CreateProfile.as_view(), name='register'),
    path('edit/', authapp.EditProfile.as_view(), name='edit'),
    path('password/edit', authapp.PasswordChange.as_view(), name='edit_password'),
    path('quick_login/<slug:slug>/', authapp.QuickLogin.as_view(), name='quick_login'),
    path('verify/<str:username>/<str:activation_key>/', authapp.VerifyRedirect.as_view(), name='verify'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('additional/', include('django.contrib.flatpages.urls')),
    re_path(r'^rosetta/', include('rosetta.urls')),
    path('', include("social_django.urls", namespace="social")),

    path('auth/', include('authapp.urls', namespace='auth')),
    path('', include('mainapp.urls', namespace='mainapp')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.EMAIL_FILE_PATH, document_root=settings.EMAIL_ROOT)

    import debug_toolbar
    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

geekshop/mainapp/urls.py
from django.urls import path, re_path
import mainapp.views as mainapp
import os
from pathlib import PurePath

app_name = PurePath(os.path.dirname(__file__)).parts[-1]

urlpatterns = [
    path('', mainapp.IndexView.as_view(), name='main'),
    path('new/', mainapp.IndexView.as_view(), name='new'),

    path('catalog/', mainapp.CatalogView.as_view(), name='catalog'),
    path('catalog/product_<int:pk>/', mainapp.ProductDetail.as_view(), name='product'),
    path('catalog/<str:href>/', mainapp.CatalogView.as_view(), name='category'),
    path('showroom/', mainapp.ErrorView.as_view(), name='showroom'),
    path('contacts/', mainapp.ContactView.as_view(), name='contacts'),
    path('search/', mainapp.SearchView.as_view(), name='search'),

    path('category/add/', mainapp.ProductCategoryCreate.as_view(), name='add_category'),
    path('category/edit/<slug:slug>', mainapp.ProductCategoryUpdate.as_view(), name='edit_category'),
    path('category/delete/<slug:slug>', mainapp.ProductCategoryDelete.as_view(), name='del_category'),

    path('product/add/', mainapp.ProductCreate.as_view(), name='add_product'),
    path('product/edit/<int:pk>', mainapp.ProductUpdate.as_view(), name='edit_product'),
    path('product/delete/<int:pk>', mainapp.ProductDelete.as_view(), name='del_product'),

    path('picture/add/<int:related_obj>', mainapp.PictureCreate.as_view(), name='add_picture'),
    path('picture/edit/<int:pk>', mainapp.PictureUpdate.as_view(), name='edit_picture'),
    path('picture/del/<int:pk>', mainapp.PictureDelete.as_view(), name='del_picture'),

    path('orders/add_<int:ware>', mainapp.OrderCreate.as_view(), name='add_order'),
    path('orders/edit_<int:ware>', mainapp.OrderUpdate.as_view(), name='edit_order'),
    path('orders/del_<int:ware>', mainapp.OrderDelete.as_view(), name='del_order'),

    path('basket/', mainapp.InvoiceDetail.as_view(), name='basket'),
    path('invoice/confirm/', mainapp.InvoiceUpdate.as_view(), name='edit_invoice'),

    path('staff/invoices/', mainapp.StaffInvoiceList.as_view(), name='staff_invoices'),
    path('staff/invoice/create/', mainapp.StaffInvoiceCreate.as_view(), name='add_staff_invoice'),
    path('staff/invoice/<int:pk>', mainapp.StaffInvoiceUpdate.as_view(), name='edit_staff_invoice'),
    path('order_formset/<int:invoice>/<int:num>/<int:ware>/', mainapp.order_formset_ajax, name='order_formset'),

]

geekshop/mainapp/models.py
from django.core.validators import MaxValueValidator
from django.db import models
from django.db.models import Sum, F, FloatField
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _

from authapp.models import ShopUser, UserStatus


class CoreQuerySet(models.QuerySet):
    """CoreQuerySet need for change initial QuerySet;
     realization soft delete for QuerySet - filter().delete()"""

    def delete(self):
        return super(CoreQuerySet, self).update(active=False)

    def hard_delete(self):
        return super(CoreQuerySet, self).delete()


class CoreManager(models.Manager):
    """change initial QuerySet and queryset for superuser in admin_panel"""

    def get_queryset(self):
        return CoreQuerySet(self.model).filter(active=True)

    def get_all_queryset(self):
        return CoreQuerySet(self.model)


class Core(models.Model):
    """docstring for Core; realization soft delete for object - get().delete()"""
    name = models.CharField(_('name'), max_length=250, blank=True)
    description = models.TextField(_('description'), blank=True)
    sort = models.IntegerField(_('sort'), default=0, null=True, blank=True)
    active = models.BooleanField(_('active'), default=True)
    all_objects = models.Manager()
    objects = CoreManager()

    def __str__(self):
        return f'{self.name}'

    @property
    def verbose_name(self):
        return self._meta.verbose_name

    @property
    def verbose_name_plural(self):
        return self._meta.verbose_name_plural

    def delete(self):
        self.active = False
        self.save()

    def hard_delete(self):
        super().delete()


class MenuPage(Core):
    """docstring for MenuPages"""
    class Meta:
        verbose_name = _('Main page')
        verbose_name_plural = _('Main pages')

    href = models.CharField(_('page url'), max_length=64, blank=False)
    objects = CoreManager()


class ProductCategoryManager(CoreManager):
    """docstring for ProductCategoryManager"""
    def get_category(self):
        return self.order_by('sort')


class ProductCategory(Core):
    """docstring for ProductCategory"""
    class Meta:
        verbose_name = _('Product category')
        verbose_name_plural = _('Product categories')

    href = models.CharField(_('page url'), max_length=64, blank=False)
    discount = models.PositiveIntegerField(verbose_name="Discount, %", default=0, validators=[MaxValueValidator(100),])
    objects = ProductCategoryManager()


class PictureManager(CoreManager):
    """docstring for  PictureManager"""

    def get_queryset(self):
        return self.get_all_queryset()

    def get_main(self):
        return self.filter(kind=self.model.DEFAULT, active=True)

    def get_inactive(self):
        return self.filter(active=False)

    def get_slider(self):
        return self.filter(kind=self.model.SLIDER, active=True)


class Picture(Core):
    """docstring for Picture"""
    class Meta:
        verbose_name = _('Picture')
        verbose_name_plural = _('Pictures')
        ordering = ('sort',)

    image = models.ImageField(upload_to='products_images')
    related_obj = models.ForeignKey(Core, verbose_name=_(u'pictures'), null=True, blank=True, related_name='pictures',
                                    on_delete=models.CASCADE)
    objects = PictureManager()

    DEFAULT = 'dft'
    SLIDER = 'sld'

    Picture_KIND_CHOICES = (
        (DEFAULT, 'Default'),
        (SLIDER, 'Picture for slider'),
    )

    kind = models.CharField(max_length=3, choices=Picture_KIND_CHOICES, default=DEFAULT)


class ProductManager(CoreManager):
    """docstring for ProductManager"""

    def get_products_slider_1(self):
        return self.filter(kind=self.model.SLIDER_1).order_by('?')

    def get_products_slider_2(self):
        return self.filter(kind=self.model.SLIDER_2).order_by('?')

    def get_products_trend(self):
        return list(self.order_by('-views', '?').select_related('category'))

    def get_products_exclusive(self):
        return list(self.filter(kind=self.model.EXCLUSIVE).order_by('?'))

    def get_products_featured(self):
        return self.filter(kind=self.model.DEFAULT).order_by('?').select_related('category')

    def get_products_new(self):
        return self.order_by('-pk').select_related('category')

    def get_product_related(self, obj):
        return self.exclude(id=obj.id).filter(category=obj.category).order_by('?').select_related('category')

    def get_products_incategory(self, href):
        return self.filter(category__href=href)


class Product(Core):
    """docstring for Product"""
    class Meta:
        verbose_name = _('Product')
        verbose_name_plural = _('Products')
        ordering = ('name',)

    category = models.ForeignKey(ProductCategory, null=True, blank=True, on_delete=models.SET_NULL)
    short_desc = models.CharField(verbose_name="Short description", max_length=200)
    quantity = models.PositiveIntegerField(verbose_name="Quantity in stock", default=0)
    views = models.PositiveIntegerField(verbose_name="Views", default=0)
    objects = ProductManager()

    DEFAULT = 'dft'
    SLIDER_1 = 'sl1'
    SLIDER_2 = 'sl2'
    EXCLUSIVE = 'exl'

    Product_KIND_CHOICES = (
        (DEFAULT, 'Default'),
        (SLIDER_1, 'Product in the 1st slider'),
        (SLIDER_2, 'Product in the 2nd slider'),
        (EXCLUSIVE, 'Exclusive product'),
        )

    kind = models.CharField(max_length=3, choices=Product_KIND_CHOICES, default=DEFAULT)

    def up_views(self):
        self.views = F('views') + 1
        self.save()


class PriceManager(CoreManager):
    """docstring for ProductManager"""

    def get_price_user(self, user):
        user_status = getattr(getattr(user, 'status', None), 'status', UserStatus.DEFAULT)
        return self.filter(group__status=user_status).first()


class Price(Core):
    """
    Prices for products. Fields:
    price_base - this is base price which input by manager
    price_user - this is real price which takes into account the base price and discount
    group - user customer status
    """
    class Meta:
        verbose_name = _('Price')
        verbose_name_plural = _('Prices')

    price_base = models.DecimalField(verbose_name="Product price, $", max_digits=8, decimal_places=2, default=0)
    price_user = models.DecimalField(verbose_name="Price with discount, $", max_digits=8, decimal_places=2, default=0)
    group = models.ForeignKey(UserStatus, verbose_name=_(u'For user with status'), null=False, related_name='prices',
                              on_delete=models.CASCADE)
    related_obj = models.ForeignKey(Core, verbose_name=_(u'prices'), null=True, blank=True, related_name='prices',
                                    on_delete=models.CASCADE)
    objects = PriceManager()

    def __str__(self):
        return f'{self.price_base}'

    @receiver(post_save, sender=ProductCategory)
    def update_changed_discount(sender, instance, **kwargs):
        """update price_user after changed discount in ProductCategory"""

        for product in Product.objects.filter(category=instance):
            list(map(lambda x: x.save(), product.prices.all()))

    def save(self, *args, **kwargs):
        discount = getattr(self.related_obj.category, 'discount', 0)
        self.price_user = self.price_base if discount == 0 else self.price_base * (100-discount) / 100
        return super().save(*args, **kwargs)


class Contact(Core):
    """docstring for Contacts"""
    class Meta:
        verbose_name = _('Contact')
        verbose_name_plural = _('Contacts')

    country = models.CharField(_('country'), max_length=64, blank=False)
    sity = models.CharField(_('sity'), max_length=64, blank=False)
    phone = models.CharField(_('phone'), max_length=32, blank=False)
    email = models.CharField(_('email'), max_length=32, blank=False)
    address = models.CharField(_('address'), max_length=250, blank=False)
    objects = CoreManager()


class InvoiceManager(models.Manager):
    """docstring for InvoiceManager"""

    def get_invoice(self):
        """this is invoice in customer's basket"""

        return self.filter(active=False).select_related('user__status').\
            prefetch_related('orders__ware__category', 'orders__ware__prices__group')

    def get_last_user_invoice(self, request):
        return self.filter(user=request.user.id).last()

    def get_staff_invoice(self, pk):
        """need only for select_related for page customer's invoice for staff"""

        return self.filter(pk=pk).select_related('user__status')

    def get_staff_invoices(self):
        return self.exclude(status=self.model.FORMING).order_by('-pk').select_related('user')

    def get_staff_invoices_count(self):
        return self.filter(status=self.model.SENT_TO_PROCEED).count()


class Invoice(Core):
    """docstring for Invoice"""
    class Meta:
        verbose_name = _('Invoice')
        verbose_name_plural = _('Invoices')

    user = models.ForeignKey(ShopUser, null=False, blank=True, related_name='invoices', on_delete=models.PROTECT)
    date_order = models.DateTimeField(verbose_name=_('Time of order'), auto_now_add=True)
    objects = InvoiceManager()

    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PAID = 'PD'
    PROCEEDED = 'PRD'
    READY = 'RDY'
    CANCEL = 'CNC'

    Invoice_STATUS_CHOICES = (
        (FORMING, 'Is forming'),
        (SENT_TO_PROCEED, 'Sent to proceed'),
        (PAID, 'Invoice paid'),
        (PROCEEDED, 'Invoice proceed'),
        (READY, 'Ready to issue'),
        (CANCEL, 'Cancel'),
        )

    status = models.CharField(max_length=3, choices=Invoice_STATUS_CHOICES, default=FORMING)

    @property
    def get_total_count(self):
        return self.orders.get_total_count() or 0

    @property
    def get_total_cost(self):
        return round(self.orders.get_total_cost(), 2)


class OrderManager(models.Manager):
    """docstring for InvoiceManager"""

geekshop/mainapp/templates/mainapp/contact_list.html
{% extends "mainapp/base.html" %}
{% load i18n %}

{% block class_page %}
    page_contacts
{% endblock %}

{% block content %}

    <header class="header_noslider padding_site">

        {% include 'mainapp/includes/inc_menu.html'%}

        <div class="slider_text group_a">
            <h2>{% trans 'Contact Us' %}</h2>
        </div>

    </header>
    <main class="content">

        <section class="block_contact_maps padding_site">
            <div class="block_img">
                {% with contacts=object_list  %}
                    {% for contact in contacts %}
                        <div class="bbB_img">
                            <div class="contact_text group_c">
                                <a class="arrow" href="#"></a>
                                <h2>{{contact.country }}</h2>
                                <h3>{% trans 'Phone:' %}</h3>
                                <p class="p_f_bold">{{ contact.phone }}</p>
                                <h3>{% trans 'Email:' %}</h3>
                                <p class="p_f_bold">{{ contact.email }}</p>
                                <h3>{% trans 'Address:' %}</h3>
                                <p>{{ contact.address }}</p>
                            </div>
                        </div>
                    {% endfor %}
                {% endwith %}

            </div>
        </section>


    </main>

{% endblock %}

geekshop/mainapp/templates/mainapp/error.html
{% extends "mainapp/base.html" %}
{% load i18n %}
{% block title %}
    {{ caption }}
{% endblock %}

{% block class_page %}
    page_contacts
{% endblock %}

{% block content %}

<header class="header_noslider padding_site">

    {% include 'mainapp/includes/inc_menu.html'%}

    <div class="slider_text group_a">
       <h2>{% trans 'Oops!' %}</h2>
    </div>

</header>
<main class="content">


    <section class="block_contact_maps padding_site">
         <div class="block_img group_c">
             <h2>{% trans 'Page in develop' %}</h2>
         </div>
    </section>


</main>

{% endblock %}

geekshop/mainapp/templates/mainapp/invoice_detail.html
{% extends "mainapp/base.html" %}
{% load staticfiles i18n %}
{% block title %}
    {{ caption }}
{% endblock %}

{% block js_script %}
    {{ block.super }}
    <script src="{% static 'js/basket.js' %}?v={{ VERSION }}"></script>
{% endblock js_script %}

{% block class_page %}
    page_contacts
{% endblock %}


{% block content %}

    <header class="header_noslider padding_site">

        {% include 'mainapp/includes/inc_menu.html'%}

        <div class="slider_text group_a">
            <h2>{% trans 'Basket' %}</h2>
        </div>

    </header>
    <main class="content">

        <section class="block_contact_maps padding_site">

            {% if object and object.orders.count %}
                {% include './order_form.html' with object_list=object.orders.all %}

                <div class="center">
                    <h2 class="total_cost">{% trans 'Total cost: ' %}<span>{{ object.get_total_cost }}</span>$</h2>
                    <br>
                    <form method="post" action="{% url 'mainapp:edit_invoice' %}">
                        {% csrf_token %}
                    <button type="submit" name="confirm" value="buy" class="order_us">{% trans 'Confirm' %}</button>
                </form>
                </div>
            {% elif messages %}
                <h2>{% trans 'Thanks for your order!' %}</h2>
                <h2>{% trans 'Our manager will contact you soon.' %}</h2>
                <h2>{% trans 'Your order number №' %}{{ invoice_number }}</h2>
            {% else %}
                <h2>{% trans 'No orders' %}</h2>
            {% endif %}
        </section>

    </main>

{% endblock %}

geekshop/mainapp/templates/mainapp/invoice_staff_form.html
{% extends "mainapp/base.html" %}
{% load staticfiles i18n %}
{% block title %}
    {{ caption }}
{% endblock %}

{% block js_script %}
    {{ block.super }}
    <script src="{% static 'js/jquery.formset.js' %}"></script>
    <script src="{% static 'js/invoice.js' %}?v={{ VERSION }}"></script>
{% endblock js_script %}

{% block class_page %}
    page_contacts
{% endblock %}

{% block content %}

    <header class="header_noslider padding_site">

        {% include 'mainapp/includes/inc_menu.html'%}

        <div class="slider_text group_a">
            <h2>{{ title }}{{ object.pk }}</h2>
        </div>

    </header>
    <main class="content">

        <section class="block_contact_maps padding_site center">
            <form method="post" action="" class="default_form_create form_invoice {% if not object %}form_invoice_no{% endif %}">
                {% csrf_token %}

                {% if object %}
                    <div class="customer_info">
                        <h3>{% trans 'Name:' %} {{ customer_full_name }}</h3>
                        <h3>{% trans 'Username:' %} {{ customer_username }}</h3>
                        <h3>{% trans 'Email:' %} {{ customer_email }}</h3>
                        <h3>{% trans 'Customer status:' %} {{ customer_status }}</h3>
                    </div>
                {% endif %}

                {{ form }}
                {{ orders.management_form }}
                {{ orders.non_form_errors }}

                <table class="table_invoice">
                    {% for form in orders %}

                        {% if forloop.first %}
                            <thead>
                            <tr>
                                {% for field in form.visible_fields %}
                                    {% if field.name != 'DELETE' %}
                                        <th>{{ field.label|capfirst }}</th>
                                    {% endif %}
                                {% endfor %}

                                {% if object %}
                                    <th>{% trans 'Cost per unit' %}</th>
                                    <th>{% trans 'Cost' %}</th>
                                    <th>{% trans 'View product' %}</th>
                                {% endif %}
                            </tr>
                            </thead>
                        {% endif %}

                        <tr class="formset_row">
                            {% include 'mainapp/includes/inc_order_formset.html' %}
                        </tr>

                    {% endfor %}
                </table>

                {% if object %}
                    <h3 class="total_cost">{% trans 'Total cost:' %} <span>{{ object.get_total_cost }}</span>$</h3>
                    <h3 class="total_count">{% trans 'Total count:' %} <span>{{ object.get_total_count }}</span></h3>
                {% endif %}

                <span class="center">
                    <button type="submit" name="confirm" value="buy" class="order_us_red">{% trans 'Save' %}</button>
                </span>
            </form>

            <a href="{% url 'mainapp:staff_invoices' %}" class="order_us">{% trans 'To orders'|upper %}</a>

        </section>

    </main>

{% endblock %}

geekshop/mainapp/templates/mainapp/invoice_staff_list.html
{% extends "mainapp/base.html" %}
{% load staticfiles i18n %}
{% block title %}
    {{ caption }}
{% endblock %}

{% block class_page %}
    page_contacts
{% endblock %}

{% block content %}

    <header class="header_noslider padding_site">

        {% include 'mainapp/includes/inc_menu.html'%}

        <div class="slider_text group_a">
            <h2>{{ title }}</h2>
        </div>

    </header>
    <main class="content">

        <section class="block_contact_maps padding_site center">

            <a href="{% url 'mainapp:add_staff_invoice' %}" class="order_us">{% trans 'Create order'|upper %}</a><br>

            {% if object_list %}

                <div class="table_invoices">
                    <span class="tr">
                        <span class="td"></span>
                        <span class="td">{% trans 'Number order ' %}</span>
                        <span class="td">{% trans 'Customer ' %}</span>
                        <span class="td">{% trans 'Status' %}</span>
                        <span class="td">{% trans 'Time of order' %}</span>
                    </span>

                    {% for object in object_list %}
                        <a href="{% url 'mainapp:edit_staff_invoice' object.pk %}"
                           class="tr {% if object.status == object.SENT_TO_PROCEED %}inv_sent_to_proceed{% endif %}">
                            <span class="td">{{ forloop.counter }}</span>
                            <span class="td">{{ object.pk }}</span>
                            <span class="td">{{ object.user }}</span>
                            <span class="td">{{ object.get_status_display  }}</span>
                            <span class="td">{{ object.date_order|date:"Y-m-d H:i:s" }}</span>
                        </a>
                    {% endfor %}
                </div>

            {% if is_paginated %}
                {% include './includes/inc_pagination.html' %}
            {% endif %}

            {% else %}
                <h2>{% trans 'No invoices' %}</h2>
            {% endif %}
        </section>

    </main>

{% endblock %}

geekshop/mainapp/templates/mainapp/order_form.html
{% load staticfiles i18n %}

{% for object in object_list %}
    <div class="block_img group_c basket_list">
        <a class="bbA_img group_c" href="{% url 'mainapp:product' object.ware.id %}">
            {% include 'mainapp/includes/inc_prod_picture_main.html' with class='product_img' product=object.ware %}
        </a>
        <p>{{ object.ware }}</p>
        <p>{% trans 'Price: ' %}
            {% for iter_price in  object.ware.prices.all %}
                {% if iter_price.group == user.status %}
                    {{ iter_price.price_user }}$
                {% endif %}
            {% endfor %}
        </p>
        <p class="count">{% trans 'Counts: ' %}<span>{{ object.count }}</span></p>
        <div>
            <form method="post" action="{% url 'mainapp:edit_order' object.ware.id %}">
                {% csrf_token %}
                <button onclick="editOrder(this);return false;" type="submit" name="count_up" value="{{ object.ware.id }}" class="order_us">{% trans '+' %}</button>
            </form>
            <br>
            <form method="post" action="{% url 'mainapp:edit_order' object.ware.id %}">
                {% csrf_token %}
                <input type="hidden" name="count_down">
                <button onclick="editOrder(this);return false;" type="submit" name="count_down" value="{{ object.ware.id }}" class="order_us">{% trans '-' %}</button>
            </form>
            <br>
            <form method="post" action="{% url 'mainapp:del_order' object.ware.id %}">
                {% csrf_token %}
                <button type="submit" name="delete" value="{{ object.ware.id }}" class="order_us">{% trans 'Delete' %}</button>
            </form>
        </div>
    </div>
{% endfor %}

geekshop/mainapp/templates/mainapp/picture_confirm_delete.html
{% extends "mainapp/base.html" %}
{% load i18n %}
{% block title %}
    {{ caption }}
{% endblock %}

{% block class_page %}
    page_contacts
{% endblock %}

{% block content %}

    <header class="header_noslider padding_site">

        {% include 'mainapp/includes/inc_menu.html'%}

        <div class="slider_text group_a">
            <h2>{% trans 'Delete picture' %}</h2>
        </div>

    </header>
    <main class="content">


        <section class="block_contact_maps padding_site">
            <div class="delete_product group_c">
                <h2>{% trans 'Do you really want to delete this?' %}</h2>
                <h2>{{ object.verbose_name }}</h2>
                <h2>{{ object.name }}</h2>
                <div class="center">
                    <img class="product_id_img" src="{{ object.image.url }}" alt="">
                </div>
                <p></p>

                <a href="{% url 'mainapp:edit_product' object.related_obj.id %}" class="order_us">{% trans 'Return back' %}</a>
                <form class="product_id" method="post" >
                    {% csrf_token %}
                    <input type="submit" value="{% trans 'Delete' %}" class="order_us" style="display: inline-block">
                </form>

            </div>
        </section>


    </main>

{% endblock %}

geekshop/mainapp/templates/mainapp/product_confirm_delete.html
{% extends "mainapp/base.html" %}
{% load i18n %}
{% block title %}
    {{ caption }}
{% endblock %}

{% block class_page %}
    page_contacts
{% endblock %}

{% block content %}

    <header class="header_noslider padding_site">

        {% include 'mainapp/includes/inc_menu.html'%}

        <div class="slider_text group_a">
            <h2>{{ caption }}</h2>
        </div>

    </header>
    <main class="content">


        <section class="block_contact_maps padding_site">
            <div class="delete_product group_c">
                <h2>{% trans 'Do you really want to delete this?' %}</h2>
                <h2>{{ object.verbose_name }}</h2>
                <h2>{{ object.name }}</h2>
                <p><img class="product_id_img" src="{{ object.pictures.get_main.0.image.url }}" alt=""></p>
                {% if current_url != 'del_category' %}
                    <a href="{% url 'mainapp:product' object.id %}" class="order_us">{% trans 'Return back' %}</a>
                {% else %}
                    <a href="{% url 'mainapp:category' object.href %}" class="order_us">{% trans 'Return back' %}</a>
                {% endif %}
                <form class="product_id" method="post" >
                    {% csrf_token %}
                    <input type="submit" value="{% trans 'Delete' %}" class="order_us" style="display: inline-block">
                </form>

            </div>
        </section>


    </main>

{% endblock %}

geekshop/mainapp/templates/mainapp/product_form.html
{% extends "mainapp/base.html" %}
{% load staticfiles i18n %}

{% block title %}
    {{ caption }}
{% endblock %}

{% block class_page %}
    page_contacts
{% endblock %}

{% block content %}

    <header class="header_noslider padding_site">

        {% include 'mainapp/includes/inc_menu.html' %}

        <div class="slider_text group_a">
            <h2>{{ caption }}</h2>
        </div>

    </header>
    <main class="content">

        <section class="block_contact_maps padding_site product_id">
            <div class="center">
                <form class="default_form_create" method="post">
                    {% csrf_token %}
                    {{ form }}
                    {{ prices.management_form }}
                    {{ prices.non_form_errors }}

                    <label>{% trans 'Prices of the product depending on the customer status:' %}</label>

                    {% for form in prices.forms %}
                        <div class="prices_in_form_product">
                            {% for hidden in form.hidden_fields %}
                                {{ hidden }}
                            {% endfor %}
                            {{ field.errors.as_ul }}

                            {% for field in form.visible_fields %}
                                {% if field.name == 'group' %}
                                <span class="not-allowed">
                                {% endif %}
                                    {{ field.label_tag }}
                                    {{ field }}
                                </span>
                            {% endfor %}
                        </div>

                    {% endfor %}
                    <input class="order_us" type="submit" value="Save">
                </form>
                {% if object %}
                    <a href="{% url 'mainapp:del_product' object.id %}" class="order_us">{% trans 'Delete'|upper %}</a>
                {% endif %}
            </div>
        </section>

        <section class="block_contact_maps padding_site">
            {% if object %}

                <h3>{% trans 'Edit pictures:' %}</h3>
                {% include 'mainapp/includes/inc_picture_edit.html' with add=True images=object.pictures.get_main %}

                {% if object.pictures.get_slider %}
                    <h3>{% trans 'Slider picture:' %}</h3>
                    {% include 'mainapp/includes/inc_picture_edit.html' with is_slider=True images=object.pictures.get_slider %}
                {% endif %}

                {% if object.pictures.get_inactive %}
                    <h3>{% trans 'Inactive pictures:' %}</h3>
                    {% include 'mainapp/includes/inc_picture_edit.html' with images=object.pictures.get_inactive %}
                {% endif %}

            {% endif %}
        </section>

    </main>

{% endblock %}